apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard