apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-zipkin
  namespace: k8s-containerized-services
  labels:
    app: k8s-service-zipkin
    environment: develop
    team: vmo-du5-java
spec:
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 660 # 11 minutes, default is 10 minutes
  revisionHistoryLimit: 12
  strategy:
    type: RollingUpdate # default
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-service-zipkin
  template:
    metadata:
      labels:
        app: k8s-service-zipkin
    spec:
      containers:
        - name: containerized-zipkin
          #image: linhpv5555/zipkin-server:latest # docker hub
          image: zipkin-server:v1.0.0 # local
          #imagePullPolicy: Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
          readinessProbe:
            tcpSocket:
              port: 9411
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9411
            initialDelaySeconds: 40
            periodSeconds: 40
            failureThreshold: 8
          startupProbe:
            tcpSocket:
              port: 9411
            initialDelaySeconds: 35
            periodSeconds: 25
            failureThreshold: 10
