version: '3'
services:
  main:
    image: tanerdiler/service-main-api
    container_name: service-main
    build:
      context: ./containerized-main
      dockerfile: Dockerfile
    ports:
      - "7503:2222"