version: '3'
services:
  accounts:
    image: tanerdiler/service-accounts-api
    container_name: service-accounts
    build:
      context: ./containerized-accounts
      dockerfile: Dockerfile
    ports:
      - "7500:2222"