version: '3'
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: service-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
