apiVersion: v1
data:
  logstash.conf: "input {\n\ttcp {\n      port => 5000\n      add_field => [ \"source\",
    \"microservice-examples-api\" ]\n      codec => json_lines\n  }\n}\nfilter {\n  if \"_jsonparsefailure\"
    in [tags] {\n      drop { }\n  }\n}\noutput {\n  elasticsearch {\n          hosts => [ \"elasticsearch:9200\"]\n          index
    => \"microservice-examples-api-%{+YYYY.MM.dd}\"\n          ssl => false\n          ssl_certificate_verification
    => false\n      }\n  }\n"
kind: ConfigMap
metadata:
  name: logstash
  namespace: k8s-containerized-services
