apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: k8s-containerized-services
spec:
  selector:
    app: k8s-service-logstash
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: tcp
    - protocol: TCP
      port: 12204
      targetPort: 12204
      name: logstash
    - protocol: TCP
      port: 5044
      targetPort: 5044
      name: tcpn