# spring:
#   cloud:
#     kubernetes:
#       enabled: true
#     loadbalancer:
#       ribbon:
#         enabled: false
#     gateway:
#       discovery:
#         locator:
#           enabled: true
# eureka:
#   client:
#     enabled: false

# containerized:
#   app:
#     name: k8s-containerized-orders.in.application-kubernetes_yml.profile.kubernetes