apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-zipkin
  namespace: k8s-containerized-services
  labels:
    app: k8s-service-zipkin
    environment: develop
    team: vmo-du5-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-zipkin
  template:
    metadata:
      labels:
        app: k8s-service-zipkin
    spec:
      containers:
        - name: containerized-zipkin
          image: linhpv5555/zipkin-server:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 9411