apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: k8s-containerized-services
spec:
  selector:
    app: k8s-service-zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411