apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-containerized-services
  name: k8s-service-discovery
  labels:
    app: k8s-service-discovery
    environment: develop
    team: vmo-du5-java
spec:
  replicas: 3
  progressDeadlineSeconds: 660 # 11 minutes, default is 10 minutes
  revisionHistoryLimit: 12
  strategy:
    type: RollingUpdate # default
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-service-discovery
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-service-discovery
    spec:
      containers:
        - name: containerized-discovery
          #image: linhpv5555/containerized-discovery:latest # docker hub
          image: containerized-discovery:v1.0.0 # locally
          #imagePullPolicy: Never
          ports:
            - containerPort: 8761
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 7
          livenessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 40
            failureThreshold: 8
          startupProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 35
            periodSeconds: 25
            failureThreshold: 10