apiVersion: v1
kind: Service
metadata:
  namespace: k8s-containerized-services
  name: discovery
spec:
  selector:
    app: k8s-service-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761