apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-gateway
  namespace: k8s-containerized-services
  labels:
    app: k8s-service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-gateway
  template:
    metadata:
      labels:
        app: k8s-service-gateway
    spec:
      containers:
        - name: containerized-gateway
          #image: linhpv5555/containerized-gateway:latest # docker hub
          image: containerized-gateway:v1.0.0 # locally
          imagePullPolicy: IfNotPresent # the image is pulled only if it is not already present locally.
          ports:
            - containerPort: 8762