version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: service-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      #- cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    mem_limit: 500m
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: service-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://localhost:9200
    depends_on:
      - elasticsearch

  zipkin:
    image: openzipkin/zipkin
    container_name: service-zipkin
    ports:
      - 9411:9411

  discovery:
    image: tanerdiler/service-discovery
    container_name: service-discovery
    build:
      context: ./containerized-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - logstash
    links:
      - logstash

#   cassandra-node-1:
#     hostname: cassandra-1
#     image: cassandra:latest
#     command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
#     expose:
#       - 7000
#       - 7001
#       - 7199
#       - 9042
#       - 9160
#  cassandra-node-2:
#    hostname: cassandra-2
#    image: cassandra:latest
#    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
#    links:
#      - cassandra-node-1:cassandra
#    expose:
#      - 7000
#      - 7001
#      - 7199
#      - 9042
#      - 9160

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./containerized-prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    #links:
    #  - discovery
    #  - gateway
    #  - accounts
    #  - products
    #  - orders
    #  - main

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
