apiVersion: v1
kind: Service
metadata:
  namespace: k8s-containerized-services
  name: containerized-orders
spec:
  selector:
    app: k8s-service-orders
  ports:
    - protocol: TCP
      port: 2226
      targetPort: 2226