apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-containerized-services
  name: k8s-service-products
  labels:
    app: k8s-service-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-products
  template:
    metadata:
      labels:
        app: k8s-service-products
    spec:
      containers:
        - name: containerized-products
          image: haunxhus/service-products-api:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 2222