apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-containerized-services
  name: k8s-service-products
  labels:
    app: k8s-service-products
    environment: develop
    team: vmo-du5-java
spec:
  replicas: 3
  minReadySeconds: 5
  progressDeadlineSeconds: 660 # 11 minutes, default is 10 minutes
  revisionHistoryLimit: 12
  strategy:
    type: RollingUpdate # default
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: k8s-service-products
  template:
    metadata:
      labels:
        app: k8s-service-products
    spec:
      containers:
        - name: containerized-products
          #image: linhpv5555/containerized-products:latest # docker hub
          image: containerized-products:v1.0.0 # local
          #imagePullPolicy: Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2227
          readinessProbe:
            httpGet:
              path: /product/actuator/health
              port: 2227
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 2227
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          startupProbe:
            tcpSocket:
              port: 2227
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5