apiVersion: v1
kind: Service
metadata:
  name: containerized-products
  namespace: k8s-containerized-services
spec:
  selector:
    app: k8s-service-products
  ports:
    - protocol: TCP
      port: 2227
      targetPort: 2227
