server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false

spring:
  application:
    name: containerized-discovery
  logstash:
    server: logstash
    #server: localhost
    port: 5000
  zipkin:
    base-url: http://zipkin:9411
    #base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms
