apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-accounts
  namespace: k8s-containerized-services
  labels:
    app: k8s-service-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-accounts
  template:
    metadata:
      labels:
        app: k8s-service-accounts
    spec:
      containers:
        - name: containerized-accounts
          image: haunxhus/service-accounts-api:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 2222
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 180
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#              scheme: HTTP
#            initialDelaySeconds: 10