apiVersion: v1
kind: Service
metadata:
  name: containerized-accounts
  namespace: k8s-containerized-services
spec:
  selector:
    app: k8s-service-accounts
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
  type: LoadBalancer
  #externalTrafficPolicy: Local
  #externalIPs:
  #  - 80.11.12.10
      #targetPort: service-accounts
  #status:
  #loadBalancer:
  #  ingress:
  #  - ip: localhost
