apiVersion: v1
kind: Service
metadata:
  name: containerized-accounts
  namespace: k8s-containerized-services
spec:
  selector:
    app: k8s-service-accounts
  ports:
    - protocol: TCP
      port: 7500
      targetPort: 2222