# spring:
#   cloud:
#     kubernetes:
#       enabled: true
# eureka:
#   client:
#     enabled: false

# containerized:
#   app:
#     name: k8s-containerized-orders.in.application-kubernetes_yml.profile.kubernetes