apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-containerized-services
  name: k8s-service-main
  labels:
    app: k8s-service-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-main
  template:
    metadata:
      labels:
        app: k8s-service-main
    spec:
      containers:
        - name: containerized-main
          image: haunxhus/service-main-api:latest
          #imagePullPolicy: Never
          ports:
            - containerPort: 2222