apiVersion: v1
kind: Service
metadata:
  namespace: k8s-containerized-services
  name: containerized-main
spec:
  selector:
    app: k8s-service-main
  ports:
    - protocol: TCP
      port: 7503
      targetPort: 2222